// bangladeshGeo.ts

export const bdGeoLocations: Record<string, Record<string, string[]>> = {
  Dhaka: {
    Dhaka: [
      "Dhaka Sadar",
      "Dhamrai",
      "Dohar",
      "Keraniganj",
      "Nawabganj",
      "Savar",
    ],
    Faridpur: [
      "Faridpur Sadar",
      "Boalmari",
      "Alfadanga",
      "Bhanga",
      "Madhukhali",
      "Sadarpur",
      "Charbhadrasan",
    ],
    Gazipur: ["Gazipur Sadar", "Kaliakair", "Kapasia", "Sreepur", "Kaliganj"],
    Gopalganj: [
      "Gopalganj Sadar",
      "Kotalipara",
      "Kashiani",
      "Muksudpur",
      "Tungipara",
    ],
    Kishoreganj: [
      "Kishoreganj Sadar",
      "Hossainpur",
      "Karimganj",
      "Tarail",
      "Pakundia",
      "Katiadi",
      "Bhairab",
      "Nikli",
      "Bajitpur",
      "Itna",
      "Mithamain",
      "Austagram",
    ],
    Madaripur: ["Madaripur Sadar", "Shibchar", "Kalkini", "Rajoir"],
    Manikganj: [
      "Manikganj Sadar",
      "Singair",
      "Shibaloy",
      "Daulatpur",
      "Harirampur",
      "Ghior",
      "Saturia",
    ],
    Munshiganj: [
      "Munshiganj Sadar",
      "Sirajdikhan",
      "Louhajang",
      "Tongibari",
      "Sreenagar",
      "Gazaria",
    ],
    Narayanganj: [
      "Narayanganj Sadar",
      "Bandar",
      "Rupganj",
      "Sonargaon",
      "Araihazar",
    ],
    Narsingdi: [
      "Narsingdi Sadar",
      "Palash",
      "Raipura",
      "Monohardi",
      "Shibpur",
      "Belabo",
    ],
    Rajbari: [
      "Rajbari Sadar",
      "Pangsha",
      "Baliakandi",
      "Kalukhali",
      "Goalando",
    ],
    Shariatpur: [
      "Shariatpur Sadar",
      "Naria",
      "Zanjira",
      "Gosairhat",
      "Bhedarganj",
      "Damudya",
    ],
    Tangail: [
      "Tangail Sadar",
      "Sakhipur",
      "Basail",
      "Madhupur",
      "Ghatail",
      "Kalihati",
      "Nagarpur",
      "Mirzapur",
      "Gopalpur",
      "Dhanbari",
      "Delduar",
    ],
  },
  Chattogram: {
    Chattogram: [
      "Chattogram Sadar (Kotowali/Double Mooring)",
      "Banshkhali",
      "Boalkhali",
      "Chandanaish",
      "Fatikchhari",
      "Hathazari",
      "Lohagara",
      "Mirsharai",
      "Patiya",
      "Rangunia",
      "Raozan",
      "Sandwip",
      "Satkania",
      "Sitakunda",
      "Karnaphuli",
      "Fatikchhari Uttar",
    ],
    CoxsBazar: [
      "Cox's Bazar Sadar",
      "Chakaria",
      "Kutubdia",
      "Moheshkhali",
      "Pekua",
      "Ramu",
      "Teknaf",
      "Ukhia",
    ],
    Cumilla: [
      "Cumilla Sadar",
      "Barura",
      "Brahmanpara",
      "Chandina",
      "Chauddagram",
      "Daudkandi",
      "Debidwar",
      "Homna",
      "Laksam",
      "Monoharganj",
      "Meghna",
      "Muradnagar",
      "Nangalkot",
      "Sadar Dakshin",
      "Titas",
      "Burichang",
      "Lalmai",
      "Bangara",
    ],
    Brahmanbaria: [
      "Brahmanbaria Sadar",
      "Akhaura",
      "Ashuganj",
      "Bancharampur",
      "Bijoynagar",
      "Kasba",
      "Nabinagar",
      "Nasirnagar",
      "Sarail",
    ],
    Chandpur: [
      "Chandpur Sadar",
      "Faridganj",
      "Haimchar",
      "Hajiganj",
      "Kachua",
      "Matlab Uttar",
      "Matlab Dakshin",
      "Shahrasti",
    ],
    Feni: [
      "Feni Sadar",
      "Chhagalnaiya",
      "Daganbhuiyan",
      "Fulgazi",
      "Parshuram",
      "Sonagazi",
    ],
    Lakshmipur: [
      "Lakshmipur Sadar",
      "Kamalnagar",
      "Raipur",
      "Ramganj",
      "Ramgati",
    ],
    Noakhali: [
      "Noakhali Sadar",
      "Begumganj",
      "Chatkhil",
      "Companiganj",
      "Hatiya",
      "Kabirhat",
      "Senbagh",
      "Sonaimuri",
      "Subarnachar",
    ],
    Bandarban: [
      "Bandarban Sadar",
      "Alikadam",
      "Naikhongchhari",
      "Rowangchhari",
      "Ruma",
      "Thanchi",
      "Lama",
    ],
    Khagrachhari: [
      "Khagrachhari Sadar",
      "Dighinala",
      "Guimara",
      "Manikchhari",
      "Matiranga",
      "Mahalchhari",
      "Panchhari",
      "Ramgarh",
    ],
    Rangamati: [
      "Rangamati Sadar",
      "Baghaichhari",
      "Barkal",
      "Belaichhari",
      "Juraichhari",
      "Kaptai",
      "Kawkhali",
      "Langadu",
      "Naniarchar",
      "Rajasthali",
    ],
  },
  Sylhet: {
    Sylhet: [
      "Sylhet Sadar",
      "Balaganj",
      "Beanibazar",
      "Bishwanath",
      "Companiganj",
      "Fenchuganj",
      "Golapganj",
      "Gowainghat",
      "Jaintiapur",
      "Kanaighat",
      "Dakshin Surma",
      "Zakiganj",
    ],
    Moulvibazar: [
      "Moulvibazar Sadar",
      "Barlekha",
      "Juri",
      "Kamalganj",
      "Kulaura",
      "Rajnagar",
      "Sreemangal",
    ],
    Sunamganj: [
      "Sunamganj Sadar",
      "Bishwamvarpur",
      "Chhatak",
      "Dakshin Sunamganj (Shantiganj)",
      "Derai",
      "Dowarabazar",
      "Jagannathpur",
      "Jamalganj",
      "Shalla",
      "Tahirpur",
      "Dharmapasha",
      "Madhyanagar",
    ],
    Habiganj: [
      "Habiganj Sadar",
      "Ajmiriganj",
      "Bahubal",
      "Chunarughat",
      "Lakhai",
      "Madhabpur",
      "Nabiganj",
      "Shayestaganj",
    ],
  },
  Rajshahi: {
    Rajshahi: [
      "Rajshahi Sadar (Boalia/Rajpara)",
      "Bagha",
      "Bagmara",
      "Charghat",
      "Durgapur",
      "Godagari",
      "Mohanpur",
      "Paba",
      "Tanore",
    ],
    Bogra: [
      "Bogra Sadar",
      "Adamdighi",
      "Dupchanchia",
      "Dhunat",
      "Gabtali",
      "Kahaloo",
      "Nandigram",
      "Sariakandi",
      "Shajahanpur",
      "Sherpur",
      "Shibganj",
      "Sonatala",
    ],
    Joypurhat: ["Joypurhat Sadar", "Akkelpur", "Kalai", "Khetlal", "Panchbibi"],
    Naogaon: [
      "Naogaon Sadar",
      "Atrai",
      "Badalgachhi",
      "Dhamoirhat",
      "Manda",
      "Mohadevpur",
      "Niamatpur",
      "Patnitala",
      "Porsha",
      "Raninagar",
      "Sapahar",
    ],
    Natore: [
      "Natore Sadar",
      "Bagatipara",
      "Baraigram",
      "Gurudaspur",
      "Lalpur",
      "Naldanga",
      "Singra",
    ],
    Chapainawabganj: [
      "Chapainawabganj Sadar",
      "Gomastapur",
      "Nachole",
      "Shibganj",
      "Bholahat",
    ],
    Pabna: [
      "Pabna Sadar",
      "Atgharia",
      "Bera",
      "Bhangura",
      "Chatmohar",
      "Faridpur",
      "Ishwardi",
      "Santhia",
      "Sujanagar",
    ],
    Sirajganj: [
      "Sirajganj Sadar",
      "Belkuchi",
      "Chowhali",
      "Kamarkhanda",
      "Kazipur",
      "Raiganj",
      "Shahjadpur",
      "Tarash",
      "Ullapara",
    ],
  },
  Khulna: {
    Khulna: [
      "Khulna Sadar",
      "Batiaghata",
      "Dacope",
      "Dighalia",
      "Dumuria",
      "Phultala",
      "Koyra",
      "Paikgacha",
      "Rupsa",
      "Terokhada",
    ],
    Jessore: [
      "Jessore Sadar",
      "Abhaynagar",
      "Bagherpara",
      "Chaugachha",
      "Jhikargacha",
      "Keshabpur",
      "Manirampur",
      "Sharsha",
    ],
    Jhenaidah: [
      "Jhenaidah Sadar",
      "Harinakundu",
      "Kaliganj",
      "Kotchandpur",
      "Moheshpur",
      "Shailkupa",
    ],
    Magura: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
    Kushtia: [
      "Kushtia Sadar",
      "Bheramara",
      "Daulatpur",
      "Khoksa",
      "Kumarkhali",
      "Mirpur",
    ],
    Meherpur: ["Meherpur Sadar", "Gangni", "Mujibnagar"],
    Narail: ["Narail Sadar", "Kalia", "Lohagara"],
    Bagerhat: [
      "Bagerhat Sadar",
      "Chitalmari",
      "Fakirhat",
      "Kachua",
      "Mollahat",
      "Mongla",
      "Morrelganj",
      "Rampal",
      "Sarankhola",
    ],
    Satkhira: [
      "Satkhira Sadar",
      "Assasuni",
      "Debhata",
      "Kalaroa",
      "Kaliganj",
      "Shyamnagar",
      "Tala",
    ],
    Chuadanga: ["Chuadanga Sadar", "Alamdanga", "Damurhuda", "Jibannagar"],
  },
  Barishal: {
    Barishal: [
      "Barishal Sadar",
      "Agailjhara",
      "Babuganj",
      "Bakerganj",
      "Banaripara",
      "Gournadi",
      "Hizla",
      "Mehendiganj",
      "Muladi",
      "Wazirpur",
    ],
    Barguna: [
      "Barguna Sadar",
      "Amtali",
      "Bamna",
      "Betagi",
      "Patharghata",
      "Taltali",
    ],
    Bhola: [
      "Bhola Sadar",
      "Borhanuddin",
      "Char Fasson",
      "Daulatkhan",
      "Lalmohan",
      "Manpura",
      "Tazumuddin",
    ],
    Jhalokati: ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
    Patuakhali: [
      "Patuakhali Sadar",
      "Bauphal",
      "Dashmina",
      "Galachipa",
      "Kalapara",
      "Mirzaganj",
      "Rangabali",
    ],
    Pirojpur: [
      "Pirojpur Sadar",
      "Bhandaria",
      "Kawkhali",
      "Mathbaria",
      "Nazirpur",
      "Nesarabad (Swarupkathi)",
      "Zianagar (Indurkani)",
    ],
  },
  Rangpur: {
    Rangpur: [
      "Rangpur Sadar",
      "Badarganj",
      "Gangachara",
      "Kaunia",
      "Mithapukur",
      "Pirganj",
      "Pirgachha",
      "Taraganj",
    ],
    Dinajpur: [
      "Dinajpur Sadar",
      "Birganj",
      "Birampur",
      "Bochaganj",
      "Chirirbandar",
      "Phulbari",
      "Ghoraghat",
      "Hakimpur",
      "Kaharole",
      "Khansama",
      "Nawabganj",
      "Parbatipur",
      "Biral",
    ],
    Gaibandha: [
      "Gaibandha Sadar",
      "Phulchhari",
      "Gobindaganj",
      "Palashbari",
      "Sadullapur",
      "Saghata",
      "Sundarganj",
    ],
    Kurigram: [
      "Kurigram Sadar",
      "Bhurungamari",
      "Chilmari",
      "Phulbari",
      "Nageshwari",
      "Rajarhat",
      "Raumari",
      "Rajibpur",
    ],
    Lalmonirhat: [
      "Lalmonirhat Sadar",
      "Aditmari",
      "Hatibandha",
      "Kaliganj",
      "Patgram",
    ],
    Nilphamari: [
      "Nilphamari Sadar",
      "Dimla",
      "Domar",
      "Jaldhaka",
      "Kishoreganj",
      "Saidpur",
    ],
    Panchagarh: ["Panchagarh Sadar", "Atwari", "Boda", "Debiganj", "Tetulia"],
    Thakurgaon: [
      "Thakurgaon Sadar",
      "Baliadangi",
      "Haripur",
      "Pirganj",
      "Ranisankail",
    ],
  },
  Mymensingh: {
    Mymensingh: [
      "Mymensingh Sadar",
      "Bhaluka",
      "Dhobaura",
      "Fulbaria",
      "Gaffargaon",
      "Gouripur",
      "Haluaghat",
      "Ishwarganj",
      "Muktagacha",
      "Nandail",
      "Phulpur",
      "Tarakanda",
      "Dakshin Gaffargaon",
    ],
    Jamalpur: [
      "Jamalpur Sadar",
      "Baksiganj",
      "Dewanganj",
      "Islampur",
      "Madarganj",
      "Melandaha",
      "Sarishabari",
    ],
    Netrokona: [
      "Netrokona Sadar",
      "Atpara",
      "Barhatta",
      "Durgapur",
      "Khaliajuri",
      "Kalmakanda",
      "Kendua",
      "Madan",
      "Mohanganj",
      "Purbadhala",
    ],
    Sherpur: [
      "Sherpur Sadar",
      "Jhenaigati",
      "Nakla",
      "Nalitabari",
      "Sreebardi",
    ],
  },
};

export const divisions = Object.keys(bdGeoLocations);
